#include "item.h"
#include <map>
#include "mediaTypes.h"

std::map<std::string, MediaDataTypes> item::definitions = {
    {"id",Integer},
    {"path",String},
    {"album_id",Integer},
    {"title",String},
    {"artist",String},
    {"artist_sort",String},
    {"artist_credit",String},
    {"album",String},
    {"albumartist",String},
    {"albumartist_sort",String},
    {"albumartist_credit",String},
    {"genre",String},
    {"composer",String},
    {"grouping",String},
    {"year",Integer},
    {"month",Integer},
    {"day",Integer},
    {"track",Integer},
    {"tracktotal",Integer},
    {"disc",Integer},
    {"disctotal",Integer},
    {"lyrics",String},
    {"comments",String},
    {"bpm",Integer},
    {"comp",Bool},
    {"mb_trackid",String},
    {"mb_albumid",String},
    {"mb_artistid",String},
    {"mb_albumartistid",String},
    {"albumtype",String},
    {"label",String},
    {"acoustid_fingerprInteger",String},
    {"acoustid_id",String},
    {"mb_releasegroupid",String},
    {"asin",String},
    {"catalognum",String},
    {"script",String},
    {"language",String},
    {"country",String},
    {"albumstatus",String},
    {"media",String},
    {"albumdisambig",String},
    {"disctitle",String},
    {"encoder",String},
    {"rg_track_gain",FloatNull},
    {"rg_track_peak",FloatNull},
    {"rg_album_gain",FloatNull},
    {"rg_album_peak",FloatNull},
    {"original_year",Integer},
    {"original_month",Integer},
    {"original_day",Integer},
    {"initial_key",String},
    {"length",Float},
    {"bitrate",String},
    {"format",String},
    {"samplerate",String},
    {"bitdepth",Integer},
    {"channels",Integer},
    {"mtime",Float},
    {"added",Float}
};

item::item()
{
}

